Feature/openrc gentoo
diodonfrost/docker-ansible pull request #3
Opened 2021-01-30 11:41 UTC by bodsch

here comes an systemd less version of gentoo :)
i personally prefer a system with openrc

2021-02-05 23:35 UTC, diodonfrost requested changes
I think you can replace the Gentoo systemd image by the Gentoo openrc.

2021-02-05 23:35 UTC, diodonfrost commented on .github/workflows/build.yml
>              version: "latest"
Openrc is the default init system of Gentoo, You can replace gentoo-systemd image by Gentoo openrc. Just keep the version to latest.

2021-02-05 23:35 UTC, diodonfrost commented on .github/workflows/push.yml
> +            platform: "linux/amd64"
same as above

2021-02-12 05:52 UTC, bodsch commented
> I think you can replace the Gentoo systemd image by the Gentoo openrc.

You are right!
I could have thought of it myself. :)
My wish was to have everything from one source if possible, that makes automated testing much easier. ;)
The PR can be closed.

2021-02-12 05:52 UTC, closed without merging